In [108]:
import pandas as pd
income_data=pd.read_csv("../data/NYC Median Income by Zipcode.csv")

In [109]:
# remove 
income_data['zipcode']=income_data.Geography.str[-6:]

In [110]:
station_data=pd.read_csv("../data/subwayszip.csv")

In [111]:
# get zipcode
station_data['zipcode']=station_data.zipcode.str[-6:]

In [23]:
# merge station name with income data
station_income=pd.merge(station_data, income_data, how='outer', on=None, left_on='zipcode', right_on='zipcode')

In [24]:
# clean up data: station names, column name, and convert income to numbers for sorting
station_income['name']=station_income.name.str.upper()
station_income.rename(columns={'Median income (dollars); Estimate; Households':'Median income'}, inplace=True)
station_income['Median income'] = pd.to_numeric(station_income['Median income'], errors='coerce')

In [26]:
# clean N/A median income values by finding nearest stations (by latitude and longitude) with income values
sort_by_zip=station_income.sort_values(by=['lat', 'long'], ascending=[True, True])
sort_by_zip.reset_index(inplace=True)
sort_by_zip.fillna(method='bfill', inplace=True)
sort_by_zip.head(5)

,index,name,zipcode,lat,long,Geography,Median income
0,365,WEST 8 STREET-NEW YORK AQUARIUM,11224,40.576034,-73.975958,ZCTA5 10012,104561.0
1,307,OCEAN PKWY,11235,40.576312,-73.968501,ZCTA5 10012,104561.0
2,368,CONEY ISLAND-STILLWELL AV STATION,11224,40.577281,-73.981236,ZCTA5 10012,104561.0
3,308,BRIGHTON BEACH,11235,40.577710,-73.961354,ZCTA5 10012,104561.0
4,367,NEPTUNE AV,11224,40.580739,-73.974593,ZCTA5 10012,104561.0

In [27]:
# clean data
sort_by_income=sort_by_zip.sort_values(by=['Median income'], ascending=False)
sort_by_income=sort_by_income.drop_duplicates(subset={'name'})

In [28]:
# station_data.name.unique()

array(['ASTOR PL', 'CANAL ST', '50 ST BROADWAY', 'BERGEN STREET STATION',
       'PENNSYLVANIA AV STATION', '238 ST',
       '110 ST-CATHEDRAL PKWY STATION', 'KINGSTON-THROOP AVS STATION',
       '65 STREET STATION', '36 STREET STATION', 'DELANCEY ST',
       'VAN SICLEN AV', 'NORWOOD AVENUE STATION', '104 STREET STATION',
       'DEKALB AV SUBWAY STA', 'BEACH 105 STREET SEASIDE',
       'BEACH 90 STREET HOLLAND', 'FREEMAN ST', 'INTERVALE AV',
       '182ND-183RD STS.', '174-175 ST STATION', '167 STREET STATION',
       'METS - WILLETS POINT', 'JUNCTION BLVD', 'MAIN ST STATION',
       'BUHRE AV', '3 AVENUE-138 STREET STATION',
       'CASTLE HILL AVENUE STATION', 'CHAMBERS ST', 'ZEREGA AV',
       'GRAND CENTRAL-42 STREET STATION', '33 STREET STATION',
       '96 STREET STATION', '77 ST', 'CHAUNCEY ST', 'UNION ST',
       'ELMHURST AV', 'RALPH AV', 'PELHAM PKWY', 'GUN HILL RD',
       'NEREID AV', 'BOTANIC GARDEN', 'SIMPSON ST',
       'BRONX PARK EAST STATION', 'WINTHROP ST',
       '149 ST - GRAND CONCOURSE', '161 ST - YANKEE STADIUM',
       '59 ST-LEXINGTON AV STATION', 'E 149 ST', 'MORRISON AV- SOUNDVIEW',
       'WHITLOCK AV', 'ST LAWRENCE AV', '61 ST-WOODSIDE',
       'FAR ROCKAWAY MOTT AVENUE STATION', '72 STREET STATION', '96 ST',
       '168 STREET STATION', 'KINGSBRIDGE ROAD SUBWAY STATION',
       '42 ST-BRYANT PARK SUBWAY STATION', 'PROSPECT PARK SUBWAY STATION',
       '55 STREET STATION', 'JAMAICA - VAN WYCK SUBWAY STATION',
       'UNION TURNPIKE - KEW GARDENS STATION',
       'SUTPHIN BLVD-ARCHER AV-JFK STATION', 'COURT SQUARE-23 ST STATION',
       '67 AVENUE STATION', 'GRAND AV-NEWTOWN STATION', 'DITMAS AV',
       'CLASSON AV', 'BROADWAY', 'METROPOLITAN AV STATION',
       'SUTTER AVENUE STATION', 'WILSON AVENUE STATION',
       'HALSEY STREET STATION', 'LORIMER ST', '8 AV', '36TH AVENUE',
       'STEINWAY STREET STATION', 'TIMES SQ-42 ST', 'PARK PL', '111 ST',
       'WEST 4 ST-WASHINGTON SQ STA', '51 ST STATION',
       '86 STREET STATION', '233 STREET STATION',
       '66 ST - LINCOLN CENTER SUBWAY STATION', 'HUNTS POINT AV',
       'CANAL ST STATION', 'MIDDLETOWN RD STATION', '23 STREET STATION',
       'COURT SQUARE STATION', '59 ST - COLUMBUS CIRCLE',
       'HUNTERS POINT AV', 'HOUSTON STREET STATION',
       '104 ST-OXFORD AV STATION', 'BROAD CHANNEL STATION', 'OCEAN PKWY',
       'VERNON BLVD - JACKSON AV', '68 STREET STATION',
       'QUEENSBORO PLAZA', 'ROCKAWAY BLVD',
       '14 STREET - UNION SQ STATION', 'BEDFORD-NOSTRAND AVS STATION',
       '15 ST - PROSPECT PARK STATION', '7 AVENUE STATION',
       'FORT HAMILTON PARKWAY STATION', 'CHURCH AV', 'BEVERLEY RD',
       'CHURCH AV STATION', 'NEWKIRK PLAZA SUBWAY STATION', 'PARKSIDE AV',
       'GRAND ARMY PLAZA STATION',
       'ATLANTIC AVENUE BARCLAYS CENTER STATION', 'ROCKAWAY AV',
       'FULTON ST', 'CLINTON-WASHINGTON AVENUES STATION', '7 AVENUE',
       'BOROUGH HALL', 'AQUEDUCT RACETRACK', 'MORRIS PARK STATION',
       'NOSTRAND AV', 'NEVINS STREET STATION',
       'EASTERN PARKWAY BROOKLYN MUSEUM STATION', 'BEVERLY RD',
       'NEWKIRK AVENUE STATION', 'FLATBUSH AVENUE STATION', 'STERLING ST',
       'UTICA AVENUE SUBWAY STATION', 'KINGSTON AV', 'NASSAU AV',
       'GREENPOINT AV', 'MARCY AV', 'HEWES ST', '138 STREET STATION',
       '5 AVE - 53 ST', 'LEXINGTON AV-53 ST', '28 ST BROADWAY',
       '34 ST - HERALD SQ SUBWAY STATION', '1 AVENUE STATION',
       'TIMES SQ-42 ST SUBWAY STATION', 'GRAHAM AV', 'BEDFORD AV STATION',
       'MONTROSE AVENUE STATION', 'COURT SQUARE',
       '21 STREET-VAN ALST STATION', '39 AVENUE STATION', '145 ST',
       '157 STREET STATION', '103 ST',
       '110 STREET STATION - CENTRAL PARK NORTH', '103 ST STATION',
       '72 STREET / BROADWAY',
       '81 STREET-MUSEUM OF NATURAL HISTORY STATION', '75 AV',
       'CATHEDRAL PARKWAY 110 STREET STATION',
       '116 STREET STATION - COLUMBIA UNIVERSITY', '125 STREET STATION',
       '135 ST', '116TH STREET STATION', 'TREMONT AV',
       '137 ST - CITY COLLEGE', '176 ST / JEROME AV',
       'BURNSIDE AV STATION', '170 STREET STATION', '181 STREET STATION',
       '191 STREET SUBWAY STATION', '175 STREET STATION',
       'BEACH 44 ST STATION / FRANK AVENUE',
       'BEACH 60 ST STATION - STRAITON AVENUE',
       'BEACH 98 STREET - PLAYLAND',
       'ROCKAWAY PARK STATION - BEACH 116 STREET',
       'BEACH 36 STREET - EDGEMERE STATION',
       'BEACH 25 STREET WAVECREST STATION', 'PARSONS BLVD',
       '169 STREET STATION', '103 ST-CORONA PLAZA STATION',
       '63 DRIVE-REGO PARK SUBWAY STATION', 'GRANT AVENUE SUBWAY STATION',
       '79 STREET STATION', 'ATLANTIC AV STATION',
       'CHRISTOPHER ST STATION', 'LEFFERTS BLVD STATION',
       'TIMES SQ - 42 ST', 'WEST 8 STREET-NEW YORK AQUARIUM',
       '28 STREET STATION', '28 STREET SUBWAY STATION', 'PELHAM BAY PARK',
       'WESTCHESTER SQ - E TREMONT AV', '18 STREET STATION',
       'BEACH 67 ST STATION ARVERNE BY THE SEA',
       '85 STREET - FOREST PARKWAY STATION', 'WOODHAVEN BLVD',
       '111 STREET STATION', '121 STREET', 'HALSEY ST STATION',
       'MYRTLE-WYCKOFF AVENUES SUBWAY STATION', 'NEW LOTS AVENUE STATION',
       'VAN SICLEN AV STATION', 'CLEVELAND ST', 'LIVONIA AV', 'JUNIUS ST',
       'ROCKAWAY AVE', 'CANARSIE-ROCKAWAY PKWY', 'E 105 ST',
       'SARATOGA AV', 'SUTTER AV - RUTLAND RD', 'NEW LOTS AV',
       'BROADWAY JUNCTION', 'ALABAMA AV', 'SHEPHERD AVENUE STATION',
       'CRESCENT ST', 'CYPRESS HILLS', '75 ST-ELDERTS LANE STATION',
       '69 ST-FISK AV STATION',
       'ROOSEVELT AV - JACKSON HEIGHTS SUBWAY STATION', 'SENECA AV',
       'DEKALB AV', '52 STREET - LINCOLN AV STATION', '46 STREET STATION',
       'NORTHERN BLVD STATION', '46 ST-BLISS ST STATION',
       '82 STREET STATION', '90 ST - ELMHURST AV',
       'HOWARD BEACH - JFK SUBWAY STATION', 'AQUEDUCT NORTH CONDUIT AV.',
       'BRIARWOOD SUBWAY STATION', 'FOREST HILLS - 71 AV', 'SUTPHIN BLVD',
       'JAMAICA CENTER - PARSONS/ARCHER', '225 STREET STATION',
       'ELDER AV', 'LONGWOOD AV STATION', 'ASTORIA BLVD STATION',
       'DITMARS BLVD STATION', 'JACKSON AVENUE STATION', 'PROSPECT AV',
       'CYPRESS AV', '174 STREET STATION', 'ALLERTON AV',
       'E 143 ST STATION', 'KINGSBRIDGE RD STATION',
       'BEDFORD PARK BLVD STATION', '148TH STREET LENOX TERMINAL STATION',
       'MT EDEN AV STATION', 'FORDHAM ROAD STATION',
       'MARBLE HILL - 225 ST', '231 ST', '215 STREET STATION',
       '207 ST STATION', 'DYCKMAN STREET SUBWAY STATION',
       'VAN CORTLANDT PARK - 242 ST',
       'WEST FARMS SQUARE - E TREMONT AV STATION', '219 STREET STATION',
       'MOSHOLU PKWY', '205 STREET STATION', 'BURKE AV STATION',
       'BAYCHESTER AV', 'EASTCHESTER - DYRE AV', 'JAMAICA-179 ST',
       '241 STREET STATION', 'BUSHWICK AV-ABERDEEN ST',
       'GUN HILL ROAD STATION', 'E 180 STREET', '125 ST',
       'FRANKLIN AV STATION', '3 AV - 149 ST', 'BROOK AV',
       '33 ST- RAWSON ST', '40 ST - LOWERY ST STATION',
       '145 STREET STATION', '155 ST', 'UTICA AV',
       'KOSCIUSZKO STREET STATION', 'GATES AVENUE STATION', 'CENTRAL AVE',
       'KNICKERBOCKER AV / MYRTLE AV', '30 AVENUE STATION',
       'JEFFERSON ST', 'MORGAN AVENUE SUBWAY STATION',
       'QUEENS PLAZA SUBWAY STATION', '18 AVENUE STATION',
       '77 STREET STATION', 'BAY RIDGE AV STATION', '50 ST',
       'FORT HAMILTON PKWY', '25 AVENUE STATION', 'BAY PARKWAY STATION',
       'BAY PKWY', 'BAY RIDGE - 95 ST', '71 ST', '20 AVENUE STATION',
       'NEW UTRECHT AV', 'AVENUE U', 'KINGS HWY', 'BRIGHTON BEACH',
       'SHEEPSHEAD BAY', 'AVENUE U STATION', 'KINGS HIGHWAY STATION',
       'NEPTUNE AV', 'AVENUE X STATION', 'BAY 50 ST STATION',
       '86 STREET SUBWAY STATION', 'AVENUE P', 'AVENUE N', 'AVENUE M',
       'AVENUE I STATION', 'AVENUE J', 'AVENUE H', 'NECK ROAD STATION Q',
       '21 ST - QUEENSBRIDGE', '50 STREET SUBWAY STATION',
       '47-50 STREETS ROCKEFELLER CENTER STATION', '57 STREET STATION',
       'LEXINGTON AV-63 STREET SUBWAY STATION',
       'ROOSEVELT ISLAND SUBWAY STATION', '49 STREET',
       '57 STREET SUBWAY STATION', '5 AVENUE STATION',
       '34 STREET - PENN STATION', 'FULTON STREET SUBWAY STATION',
       'CHAMBERS STREET STATION', '42 ST - PORT AUTHORITY BUS TERMINAL',
       'MYRTLE - WILLOUGHBY AVS', 'HOYT - SCHERMERHORN',
       'JAY ST - METROTECH STATION', 'EAST BROADWAY', '2 AVENUE STATION',
       'FLUSHING AV', 'MYRTLE AV STATION', '4 AV - 9 ST STATION',
       'SMITH-9TH STREET', 'BERGEN ST STATION', 'JAY ST - METROTECH',
       'COURT STREET STATION', 'PROSPECT AV STATION', '9 STREET STATION',
       '3 AVENUE STATION', 'LIBERTY AVENUE STATION', '59 STREET STATION',
       '45 ST STATION', '9 AVENUE', '53 STREET STATION', '25 ST',
       'CARROLL ST STATION', 'SPRING STREET SUBWAY STATION', '181 ST',
       '190 STREET SUBWAY STATION', '116 ST', 'PRINCE ST STATION',
       '8 STREET STATION', 'FULTON STREET STATION', 'WORLD TRADE CENTER',
       'HOYT ST', '183 STREET STATION', 'CANAL STREET STATION',
       '163 STREET SUBWAY STATION', 'CITY HALL',
       'CANAL STREET SUBWAY STATION', 'SOUTH FERRY STA', 'BOWLING GREEN',
       'WALL STREET STATION', 'WHITEHALL ST', 'RECTOR ST',
       'FRESH POND ROAD STATION', 'MIDDLE VILLAGE - METROPOLITAN AV',
       'CORTLANDT STREET STATION', 'BROAD ST', 'BOWERY STATION',
       'BROADWAY-LAFAYETTE ST STATION', '34 ST - PENN STATION',
       '14 STREET STATION', '135 STREET STATION', '14 ST',
       'NOSTRAND AVENUE STATION', 'CLARK STREET SUBWAY STATION',
       'CLINTON - WASHINGTON AVE', 'FOREST AV', '110 ST',
       '86 ST LEXINGTON AV', 'YORK STREET SUBWAY STATION',
       'LAFAYETTE AVENUE STATION C', 'PRESIDENT STREET STATION',
       'EUCLID AV STATION', '88 ST-BOYD AV STATION', 'CORTELYOU RD',
       '116 STREET STATION', 'PARKCHESTER', 'FRANKLIN ST', '80 ST',
       '5 AVENUE-BRYANT PARK STATION', 'SPRING ST SUBWAY STATION',
       '125 STREET SUBWAY STATION', 'CONEY ISLAND-STILLWELL AV STATION',
       '34TH STREET-HUDSON YARDS SUBWAY STATION',
       '72 STREET SUBWAY STATION', '96 ST & 2 AVENUE'], dtype=object)

In [29]:
# list of top 10 stations from MTA data anlaysis
top10_stations=['34 STREET - PENN STATION', 'GRAND CENTRAL-42 STREET STATION',  '34 ST - HERALD SQ SUBWAY STATION',  '14 STREET - UNION SQ STATION', 'TIMES SQ-42 ST SUBWAY STATION',  '23 STREET STATION',  'FULTON ST', '42 ST - PORT AUTHORITY BUS TERMINAL', '86 STREET STATION', '125 ST']

In [30]:
# List of top 10 traffic stations and the corresponding median income
sort_by_income.loc[sort_by_income['name'].isin(top10_stations)]

,index,name,zipcode,lat,long,Geography,Median income
146,23,FULTON ST,11217,40.687119,-73.975375,ZCTA5 10004,140450.0
361,280,86 STREET STATION,10024,40.788644,-73.976218,ZCTA5 10024,126107.0
276,292,23 STREET STATION,10011,40.742954,-73.992765,ZCTA5 10011,123208.0
311,126,GRAND CENTRAL-42 STREET STATION,10017,40.752769,-73.979189,ZCTA5 10017,118469.0
303,442,34 STREET - PENN STATION,10120,40.750373,-73.991057,ZCTA5 10017,118469.0
263,2,14 STREET - UNION SQ STATION,10003,40.735872,-73.990539,ZCTA5 10003,104441.0
321,262,TIMES SQ-42 ST SUBWAY STATION,10036,40.755983,-73.986229,ZCTA5 10036,93707.0
326,266,42 ST - PORT AUTHORITY BUS TERMINAL,10036,40.757308,-73.989735,ZCTA5 10036,93707.0
299,333,34 ST - HERALD SQ SUBWAY STATION,10001,40.749645,-73.987937,ZCTA5 10001,85221.0
385,343,125 ST,10027,40.815581,-73.958372,ZCTA5 10027,45536.0